# Completely disable yarn
enableGlobalCache: false
enableImmutableInstalls: false
enableInlineBuilds: false
enableScripts: false
enableStrictSsl: false
# Force version that doesn't exist
yarnPath: "nonexistent"
version: "0.0.0"
