services:
  - type: web
    name: electrical-3-y99h
    env: node
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_TYPE
        value: sqlite
      - key: DB_PATH
        value: ./electrical_management.db
      - key: FRONTEND_URL
        value: https://super-paprenjak-d9ab2f.netlify.app
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    plan: free
