services:
  - type: web
    name: derelectrical-3-y99h
    env: node
    buildCommand: |
      echo "=== FORCING COMPLETE CLEAN INSTALL ==="
      echo "Removing all cached files..."
      rm -f yarn.lock package-lock.json
      rm -rf .yarn node_modules
      rm -f .yarnrc .yarnrc.yml
      echo "Clearing npm cache completely..."
      npm cache clean --force
      echo "Installing Express 4.18.2 specifically..."
      npm install express@4.18.2 --save --no-package-lock
      echo "Installing other dependencies..."
      npm install --only=production --no-package-lock
      echo "Verifying Express version..."
      npm list express
      echo "=== BUILD COMPLETED ==="
    startCommand: npm run start:minimal
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_TYPE
        value: sqlite
      - key: DB_PATH
        value: ./electrical_management.db
      - key: FRONTEND_URL
        value: https://electrical-3.netlify.app
      - key: NPM_CONFIG_PACKAGE_MANAGER
        value: npm
      - key: YARN_DISABLE
        value: "true"
      - key: NPM_CONFIG_ENGINE_STRICT
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    plan: free
